### ISSUE TITLE
What language shall it be written in?

### ISSUE THREAD

**Issue by CrazyPython** [vsl-lang/VSL#1]
One argument for each language. Use the emoji react to vote.

**Comment by CrazyPython** [comment]
# PyPy
## Pros
 - **Performance** - almost as fast as Java or C++
 - **Readable + easy to write in** - this is the only language with this feature that's also performance
 - **Many libraries, large community**
## Cons

**Comment by vihanb** [comment]
It's pretty much between C & C++ since we're using Flex/Bison, and between those too `C++` is the clear choice imo. No one can code something as complex as this in `C`

**Comment by vihanb** [comment]
I've also setup project up as C++ :|

**Comment by tuxcrafting** [comment]
I prefer C TBH

**Comment by CrazyPython** [comment]
@vihanb Then don't use Flex/Bison

**Comment by tuxcrafting** [comment]
Flex/Bison is needed to make clear parsing code

**Comment by vihanb** [comment]
C code is valid C++ code

**Comment by CrazyPython** [comment]
@tuxcrafting I don't believe Python uses Flex/Bison

**Comment by vihanb** [comment]
I think classes and namespaces are important

**Comment by tuxcrafting** [comment]
No, `struct`s are different

**Comment by CrazyPython** [comment]
# C
## Cons
- C++ is better and has the same performance

**Comment by tuxcrafting** [comment]
@CrazyPython IDK, but TBH I prefer Flex/Bison

**Comment by vihanb** [comment]
we've already descided on language too, closing...

**Comment by tuxcrafting** [comment]
@CrazyPython Cons: Hardly interfacable with C

**Comment by CrazyPython** [comment]
@vihanb Flex/Bison is possible with other languages. http://freenet.mcnabhosting.com/python/pybison/

**Comment by CrazyPython** [comment]
# VSL
## Pros
 - We can change it however we want
 - It's good because we made it
 - CFront, the original C++ compiler, was written in C++.

**Comment by CrazyPython** [comment]
# RPython
## Pros
 - For interpreters
 - Fast for production apps like PyPy
 - Statically typed

## Cons
 - No braces

**Comment by CrazyPython** [comment]
# Brainf**k
## Pros
 - A huge library & community
 - Easy to write in
 - Production apps like <s>nothing</s> EVERYTHING
 - Free + open source
 - Tastes like bacon
 - Non-GMO, 100% Organic, and free-range
## Cons
 - There are none.
