### ISSUE TITLE
Class initalizers

### ISSUE THREAD

**Issue by vihanb** [vsl-lang/VSL#2]
Classes don't have initalizers, they'll need to support:
 - Optional returns `init?`
 - Compilation `<name>.init.<params>`

Validation and other problems are to be solved.

Examples:

```swift
public init?(a: T?) {
    if a == T.b { return nil }
    self.a = a
}
```

Additionally field initalization and `super()` order checks should be implemented

**Comment by somebody1234** [comment]
I don't think `init` is a good idea, IMO we should make it like C# and make constructor name same as class name, plus `return`s with a value aren't allowed in initializers

**Comment by vihanb** [comment]
@somebody1234 it is nullable intalizer so that why it is returning

**Comment by vihanb** [comment]
as for `init()` vs `ClassName()` that is another discussion

**Comment by vihanb** [comment]
shit wrong issue :||||

**Comment by taylorhansen** [comment]
Wrong issue. :P

**Comment by taylorhansen** [comment]
So I take it that the constructor syntax would be something like this then:
```swift
public class A {
    public init?(args) {
        self(other args)
        if(something bad) {
            return nil
        }
    }

    private init(args) {
        super(other args)
        do some stuff
    }
}
```

**Comment by vihanb** [comment]
that looks good. (the `init(args)`) would probably need to specify types but I assume you're using the function param list for initalizers anyway
