### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by taylorhansen** [vsl-lang/VSL#26]
As of 690589b049d232641d5b6794c59221c122170619, the codecov score on this repo is _**24%**_. If we want to be sure that new code doesn't break anything, we need to improve that score up to 90-100% with a lot more test cases.

**Comment by vihanb** [comment]
Our code coverage is 33% atm, 90%-100% is out of scope for this phase of VSL, I'd head for 70%-80%ish.

**Comment by taylorhansen** [comment]
I guess I was looking at master then. Edited. For [develop](https://codecov.io/gh/vsl-lang/VSL/branch/develop), codecov says about 24% by the way.

**Comment by vihanb** [comment]
you should use the build logs: https://travis-ci.org/vsl-lang/VSL/jobs/240450761#L1689 because codecov never has any idea what is going on

**Comment by taylorhansen** [comment]
I think you're looking at the `% Stmts` or the `% Lines` part. Regardless, it's still an issue with the current test cases.
