### ISSUE TITLE
How will VSL be different from other scripting languages?

### ISSUE THREAD

**Issue by CrazyPython** [vsl-lang/VSL#3]
*note:* this document was created to *motivate* and to make sure VSL doesn't go off course, not to be negative

- Performance (performance for a scripting language)
- Readability (most scripting languages are readable)

Freely edit this.

**Comment by vihanb** [comment]
imo this should be in README

**Comment by CrazyPython** [comment]
@vihanb or in a hack.md, but this is for discussion :/

**Comment by CrazyPython** [comment]
@vihanb why VSL, why not something else? This is what it asks.
