### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by tuxcrafting** [vsl-lang/VSL#4]
Let's keep it simple:

![vsllogo](https://cloud.githubusercontent.com/assets/12471641/19453531/f5001b94-94b5-11e6-97e9-8c5741a30a3d.png)

Comment on this issue to comment on this logo/propose a new logo

**Comment by CrazyPython** [comment]
@tuxcrafting the name "vsl" might need to be changed.

**Comment by tuxcrafting** [comment]
@CrazyPython Why?

**Comment by CrazyPython** [comment]
@tuxcrafting long, generic, hard to pronounce, three syllables. 

If it's just a text font, I'd use a softer font.

Maybe a scroll with "VSL" on it?

**Comment by vihanb** [comment]
I'm sure we could make a much cooler logo but what are defining characteristics of VSL which we can embody within a logo?

**Comment by vihanb** [comment]
What colors should we use? Orange / White? Cyan / White?

**Comment by vihanb** [comment]
<img width="460" alt="screen shot 2016-10-17 at 6 26 52 pm" src="https://cloud.githubusercontent.com/assets/15314511/19461180/4e1607bc-9497-11e6-8c72-9a0802031486.png">

**Comment by vihanb** [comment]
ignore blue x in the middle

**Comment by vihanb** [comment]
I can make the S's tail merge into the V

**Comment by vihanb** [comment]
alternative:

<img width="294" alt="screen shot 2016-10-17 at 6 37 51 pm" src="https://cloud.githubusercontent.com/assets/15314511/19461354/d75f1792-9498-11e6-8504-432b64461d70.png">

**Comment by vihanb** [comment]
<img width="476" alt="screen shot 2016-10-17 at 6 50 16 pm" src="https://cloud.githubusercontent.com/assets/15314511/19461890/556de3a8-949d-11e6-90fc-3d37974b08b8.png">

**Comment by CrazyPython** [comment]
@vihanb oh my god that looks awesome. First one is my choice. Change the VSL Org profile pic.

**Comment by CrazyPython** [comment]
Also, what font is that?

**Comment by somebody1234** [comment]
@vihanb Yes the second last one

**Comment by CrazyPython** [comment]
My ranking (let's not do first past the post):
first one
third one
second one

**Comment by vihanb** [comment]
<img width="930" alt="screen shot 2016-10-18 at 5 26 43 pm" src="https://cloud.githubusercontent.com/assets/15314511/19501154/123beaba-9558-11e6-9253-d806e73ad40f.png">

Pls vote by doing:
 - 👍 for Top Left
 - 😄 for Top Right
 - ❤️ for Bottom

**Comment by CrazyPython** [comment]
I voted twice, First Past The Post is usually a bad voting strategy.

**Comment by CrazyPython** [comment]
It looks like we have a winner!
