### ISSUE TITLE
Rewrite the parser in C++

### ISSUE THREAD

**Issue by tuxcrafting** [vsl-lang/VSL#7]
The title is pretty self-explanatory. It would be good because OO code is more easily extensible than pure imperative code.

**Comment by tuxcrafting** [comment]
Or, as quartata [said in chat](https://chat.stackexchange.com/transcript/message/33018679#33018679), we could write it in Objective-C instead

**Comment by vihanb** [comment]
Objective c is not as universal or idk what word to use by cpp is much more popular / prevailnt

**Comment by tuxcrafting** [comment]
@vihanb Objective-C is more backward compatible with C and cross-platform stdlibs for it exists

**Comment by CrazyPython** [comment]
Objective-C is a bit finicky in my experience. What about C#?

**Comment by vihanb** [comment]
@CrazyPython C# is a nice language from what I've seen but it's proprietary unfortunately. C++ is outrbest bet

**Comment by tuxcrafting** [comment]
@vihanb Roslyn and Mono are open-source, but the problem with C# is that it run on a VM

**Comment by vihanb** [comment]
@tuxcrafting ;_; VM = slow
Example: JVM

**Comment by vihanb** [comment]
Is VSL, JIT?

**Comment by tuxcrafting** [comment]
@vihanb VSL will probably be JIT'd
And VM don't necessarly mean slow. CIL VMs are generally pretty fast

**Comment by tuxcrafting** [comment]
And TBH I'd prefer to rewrite the parser in C# because C#'s generics are not messed up like C++'s one

**Comment by tuxcrafting** [comment]
And syntax is neater IMO

**Comment by vihanb** [comment]
;_; y u sai templaet is mesed up

**Comment by somebody1234** [comment]
@tuxcraftign pls even 1.5x slowdown is terrible, use C++ (also we want easy, but not 1. RAM-eating 2. battery-draining 2. so easy that it has to have GC to work and you can't avoid nor force GC)

**Comment by tuxcrafting** [comment]
@somebody1234 Plz no typo my name and C# is not necessarly RAM-eating

**Comment by somebody1234** [comment]
@tuxcrafting Well, it's *really* hard to make C# as fast as C++ plus **no bison ;_; ;_:**

**Comment by tuxcrafting** [comment]
@somebody1234 Y'know, parser generators exists for C#

**Comment by vihanb** [comment]
@tuxcrafting but flex bison is best parser generator

**Comment by tuxcrafting** [comment]
@vihanb There is flex/bison clones for C#

**Comment by vihanb** [comment]
But they might/probably aren't as good

**Comment by tuxcrafting** [comment]
@vihanb They are good

**Comment by vihanb** [comment]
But c++ is more portable

**Comment by tuxcrafting** [comment]
@vihanb Since C# run on a VM, it's only needed to compile it one time

**Comment by somebody1234** [comment]
But C# is run on a VM meaning really slow

**Comment by tuxcrafting** [comment]
@somebody1234 VMs are generally JIT'd, so they are pretty fast. And CLI is faster than JVM (Hopefully)

**Comment by CrazyPython** [comment]
vihan supposedly unborked the parser
